### ISSUE TITLE
Local database issue : Release IMo_v2.1_2023_11_30

### ISSUE THREAD

**Issue by ecarinos** [ziotom78/libinsdb#13]
Hi, I have encountered some issues with the latest IMo release (Release IMo_v2.1_2023_11_30) and the different modifications made to IMo_LiteBIRD. I have detailed some of my issues here :

https://github.com/litebird/IMo_LiteBIRD/issues/3#issuecomment-2017677726
The transition from IMo_LIteBIRD to libinsdb with the newest version of the IMo installed locally doesn't seem to work as intended. Moreover, when I "trick" libinsdb by changing the .json file name to just "schema.json", the file loads but when I try to query data from it I get the following error : 

`KeyError: 'wrong path: "IMo_v2.1_2023_11_30/PLM/Observation/Observation_Time" points to quantity "Observation_Time", which does not have data files belonging to release "IMo_v2.1_2023_11_30" (data files are: )'
`

This problem doesn't happen on previous versions of the IMo or when I use the RemoteInsDb.

**Comment by ecarinos** [comment]
The script used is the one in the IMo_LiteBIRD tutorial notebook : https://github.com/litebird/IMo_LiteBIRD/blob/main/tutorials/instrument_loading_example.ipynb, without providing the server adress in order to force local access. The error happens when I call the libinsdb.local.query_data_file method of LocalInsDb with the path indicated in the error message above.

**Comment by ziotom78** [comment]
Hi Emile, I have implemented PR #14, may you please test it and see if the problem with the file name of the JSON is fixed? If it is so, I'll release version 0.7.3 immediately.

**Comment by ecarinos** [comment]
I've tested it, the first problem with the JSON file name is fixed. I properly get the new error message but this is because I didn't export the database with InstrumentDB. Oddly enough, I think I was able to work with IMo_LiteBIRD and IMo_perf using only the previous version of the JSON file. Anyways, now we just have to modify the IMo_LiteBIRD instructions for people who want to work on a local copy of the IMo.

**Comment by ziotom78** [comment]
That's great! I'll merge the PR and release version 0.7.3 in a moment.

Regarding the reason why the code worked with the older versions, this is probably because before the version released last September, most of the useful information was saved in the `metadata` field of the quantities `instrument_info`, `detector_info`, etc., which were used by the LiteBIRD Simulation Framework. In September, version 2.1 removed those quantities; I reckon that the newer releases of IMo_LiteBIRD stopped using those quantities, but it's better if you check this with Sophie.
